apiVersion: scan.clusterscandemo.com/v1alpha1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: clusterscan-operator
    app.kubernetes.io/managed-by: kustomize
  name: test-scan
  namespace: default
spec:
  schedule: ""
  jobTemplate:
    template:
      spec:
        containers:
        - name: scan
          image: busybox
          command: ["echo", "Hello Kubernetes!"]
        restartPolicy: OnFailure
