apiVersion: scan.clusterscandemo.com/v1alpha1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: clusterscan-operator
    app.kubernetes.io/managed-by: kustomize
  name: security-scan
  namespace: default
spec:
  schedule: "" #can be run in a schedule as a cron job e.g: weekly security scan
  jobTemplate:
    template:
      spec:
        containers:
        - name: trivy-scan
          image: aquasec/trivy:latest
          command: ["trivy", "image", "--no-progress", "nginx:latest"]
        restartPolicy: OnFailure